# Generated by Django 4.1.5 on 2023-01-25 16:55

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='format: required, letters, numbers, underscores, hyphens', max_length=150, verbose_name='Category safe url'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='Format: required, max-255', max_length=255, unique=True, verbose_name='Product safe url')),
                ('name', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='Product name')),
                ('description', models.TextField(help_text='format: required', verbose_name='Product description')),
                ('is_active', models.BooleanField(default=True, help_text='format: True+ product visible', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-M-d H:M:s', verbose_name='date product created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-M-d H:M:s', verbose_name='date product updated')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.category')),
            ],
        ),
    ]
